version: ~> 1.0
dist: xenial
language: cpp
os: linux

git:
  submodules: true
  quiet: true

cache:
  ccache: true

# https://docs.travis-ci.com/user/languages/c/#gcc-on-linux
jobs:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Release
        - CMAKE_VERSION=3.8.2
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Release
        - CMAKE_VERSION=3.8.2
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - BUILD_TYPE=Release
        - CMAKE_VERSION=3.8.2
        - CXXFLAGS="-std=c++2a"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - |
    HOME_BIN_PATH=`realpath ~/bin`
    mkdir -p ${HOME_BIN_PATH}
  - |
    # install cmake
    mkdir -p /tmp/cmake-download
    wget --no-clobber --directory-prefix=/tmp/cmake-download/ https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
    tar -C /tmp/ -zxvf /tmp/cmake-download/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
    export PATH="/tmp/cmake-${CMAKE_VERSION}-Linux-x86_64/bin:${PATH}"
  - ccache --version
  - $CXX -v
  - cmake --version
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
script:
  - make -k -j2
  - |
    ctest . --output-on-failure
after_script:
  - ccache -s

